include $(TOPDIR)/rules.mk

PKG_VERSION:=1.26.3

LUCI_TITLE:=LuCI Support for Exodus
LUCI_DEPENDS:=+luci-base +exodus

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
