name: build-packages

on:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.arch }}-${{ matrix.branch }} build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64_cortex-a53
          - aarch64_generic
          - aarch64_cortex-a72
          - aarch64_cortex-a76
          - mipsel_24kc
          - arm_cortex-a7_neon-vfpv4
        branch:
          - openwrt-24.10
          - openwrt-25.12
          - SNAPSHOT

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.branch }}
          FEEDNAME: exodus
          PACKAGES: mihomo-meta exodus luci-app-exodus
          NO_REFRESH_CHECK: true

      - name: upload
        uses: actions/upload-artifact@v7
        with:
          name: exodus_${{ matrix.arch }}-${{ matrix.branch }}
          path: bin/packages/${{ matrix.arch }}/exodus
